[package]
name = "rs-minecraft-exporter"
version = "0.1.0"
authors = ["Marvin Altemeier <marvin.altemeier@hetzner-cloud.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
