[package]
name = "rs-minecraft-exporter"
version = "0.1.0"
authors = ["Marvin Altemeier <marvin.altemeier@hetzner-cloud.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus = "0.8"
serde_json = "1.0.50"
serde = { version = "1.0.50", features = ["derive"] }
log = "0.4.8"
